### PR TITLE
Updated Onboarding

### PR DESCRIPTION
**Pull request by Waidhoferj**
Combines the `ColumnScreen` and `ChartChooser` into a single `OnboardingWidget`.

## Changes
- [x] Updated header with directions / hints
- [x] Chart browser scrolls vertically to save space and avoid sizing issues
- [x] Added double click tooltip to chart
- [x] Snap scrolling on charts
- [x] Persistent column choices when navigating back to original screen
- [x] Mark filter that allows user to toggle available marks in charts to browse
- [x] Resize support for smaller screen sizes > 600px in width
- [x] Keyboard navigation for column selection
- [x] Keyboard navigation for chart selection
- [x] Keyboard navigation between column and chart selection

### CODE REVIEW

**Comment by Waidhoferj** [comment]
## Keyboard Navigation
- Select with `Space`.
- `ArrowUp` and `ArrowDown` goes to previous and next focusable element.
- On the `OnboardingScreen`, `ArrowLeft` is mapped to focusing the search bar, essentially jumping to the left column.
- On the `OnboardingScreen`, `ArrowRight` is mapped to focusing the first graph, essentially jumping to the right column.

See `KeyboardNav.ts` for the `useKeyboardNavigation` hook implementation details.

**Comment by Waidhoferj** [comment]
Fixes #59

**Review by jahn96 — COMMENTED** [review]
UI comments
1. Header for chart recommendation
2. Bounding box around the list of columns on onboading
    * We need to be clear about the relationship between the list of columns and search bar.
3. Can't see the border around the graph on click.
    * Would it better to select the chart on click instead?
4. Glitch on the bottom left corner of the chart on hover.
Screen Shot 2021-07-28 at 1 40 23 PM
5. Using enter key to check/uncheck the input box / select the chart instead of enter? Space bar is not really intuitive for me.

**Comment by Waidhoferj** [comment]
@jahn96 I fixed the UI issues

**Review by jahn96 — CHANGES_REQUESTED** [review]
I think it works fairly well. One thing I found was that clicking a chart filter button showed below:
Screen Shot 2021-07-30 at 9 29 58 AM
Should we show all charts when none of the charts is filtered?
Also, can we remove the drop shadow on the button when none of the charts is filtered?

**Comment by jahn96** [comment]
Thanks!

**Pull request merged**
