### PR TITLE
Axis Scaling

### PR DESCRIPTION
**Pull request by Waidhoferj**
**Added axis scaling for quantitative values in the `FilterScreen`**

## Changes
- Dropdown select field in filter screen

## Testing
- Go to the filter screen for a quantitative variable.
- Apply the axis scale
- Verify that the axis has been altered in scale

### CODE REVIEW

**Comment by Waidhoferj** [comment]
Fixes #69

**Review by jahn96 — COMMENTED** [review]
Code looks good!
Future Works:
1. Change the axis label on graphs.
2. Indicate transformation on exported queries

**Comment by Waidhoferj** [comment]
Got it, added axis labels. If it looks good feel free to merge!

**Comment by jahn96** [comment]
Thanks!

**Pull request merged**
